# sales_bot_app.py
import streamlit as st
from sales_bot_core import (
    route_question, 
    get_profit_by_region, 
    get_profit_margin_by_category
)

# ==============================
# Page Config
# ==============================
st.set_page_config(
    page_title="Business Insights Bot",
    page_icon="📊",
    layout="centered",
    initial_sidebar_state="expanded"
)

# ==============================
# Sidebar
# ==============================
st.sidebar.header("Business Insights Bot")
st.sidebar.write(
    """
    Ask questions about:
    - Profit by region
    - Profit margin by category
    - Total profit or sales
    """
)
st.sidebar.write("---")
st.sidebar.write("Developed by Aniket Gaikwad 🚀")

# ==============================
# Main Title & Description
# ==============================
st.markdown(
    "<h1 style='text-align: center; color: #4B0082;'>📊 Business Insights Bot</h1>", 
    unsafe_allow_html=True
)
st.markdown(
    "<p style='text-align: center; font-size:16px;'>Ask about profit, margin, or sales and get professional insights generated by AI.</p>",
    unsafe_allow_html=True
)

# ==============================
# Session State for Chat History & Last Chart
# ==============================
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "last_chart" not in st.session_state:
    st.session_state.last_chart = None  # can be "profit_region" or "profit_margin"

# ==============================
# Chat Input
# ==============================
with st.form(key="chat_form"):
    user_input = st.text_input(
        "Type your question here:", 
        key="user_question_input", 
        placeholder="e.g., Show me profit by region"
    )
    submit_button = st.form_submit_button("Get Insight")

# ==============================
# Handle Submission
# ==============================
if submit_button and user_input.strip() != "":
    # Get GPT-2 response
    response = route_question(user_input)

    # Determine which chart to show
    question_lower = user_input.lower()
    if "profit by region" in question_lower or "region profit" in question_lower:
        st.session_state.last_chart = "profit_region"
    elif "profit margin" in question_lower or "margin by category" in question_lower:
        st.session_state.last_chart = "profit_margin"
    else:
        st.session_state.last_chart = None

    # Save chat
    st.session_state.chat_history.append({"user": user_input, "bot": response})
elif submit_button:
    st.warning("Please enter a question!")

# ==============================
# Display Chat History
# ==============================
st.subheader("💬 Chat")
for chat in reversed(st.session_state.chat_history):
    st.markdown(
        f"<div style='text-align: right; color: #1E90FF;'><b>You:</b> {chat['user']}</div>", 
        unsafe_allow_html=True
    )
    st.markdown(
        f"<div style='text-align: left; color: #228B22;'><b>Bot:</b> {chat['bot']}</div>", 
        unsafe_allow_html=True
    )
    st.markdown("---")

# ==============================
# Display Dynamic Chart Based on Question
# ==============================
if st.session_state.last_chart == "profit_region":
    st.subheader("📈 Profit by Region")
    profit_region = get_profit_by_region()
    st.bar_chart(profit_region)

elif st.session_state.last_chart == "profit_margin":
    st.subheader("📈 Profit Margin by Category (%)")
    profit_margin_category = get_profit_margin_by_category()
    st.bar_chart(profit_margin_category)

# ==============================
# Footer
# ==============================
st.markdown(
    "<p style='text-align:center; font-size:12px; color:gray;'>💡 Tip: Ask precise questions for better insights. Charts appear based on your question.</p>",
    unsafe_allow_html=True
)
